### ISSUE TITLE
Style elements via css

### ISSUE THREAD

**Issue by mayurankv** [mugiwara85/CodeblockCustomizer#24]
Sorry for the many issues! It would be good to avoid hardcoding element styles and instead apply the styles to the classes of the elements.

**Comment by mugiwara85** [comment]
? What is hardcoded? Styles are applied via css

**Comment by mayurankv** [comment]
As I understand it, currently css variable like `--header-color` and so on are directly added as html rather than via css for that element. (Apologies if my plugin is outdated and this has been changed).

For example, doing. Quick inspect element gives me:

```html
<div class="codeblock-customizer-header-language-tag" style="--codeblock-lang-background-color:#B8B5AA; --codeblock-lang-color:#C25F30; --codeblock-lang-bold:bold; --codeblock-lang-italic:italic;">JavaScript</div>
```

And this style parameter could also be applied by the css

```css
.codeblock-customizer-header-language-tag {
    --codeblock-lang-background-color:#B8B5AA;
    --codeblock-lang-color:#C25F30;
    --codeblock-lang-bold:bold;
    --codeblock-lang-italic:italic;
}
```

It would be fine to leave it as is and I may be overlooking a reason for adding this directly via html but for myself it means I have to add `!important` to my css styles to override these settings. (I know that these can be themed via the plugin but I am using css variables consistent with the rest of my theme so changes only need to be made in one place).
