### ISSUE TITLE
Remove unnecessary css which controls the header width

### ISSUE THREAD

**Issue by viocha** [mugiwara85/CodeblockCustomizer#62]
When the width is enabled, the header do not align with the codeblock.
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/66580331/7184f8d4-2232-4b99-b53d-ad56b316b776)
When the width is disabed, it gets back to the normal appearance.
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/66580331/9ce4902e-5584-4729-a272-ef467d4c712d)
The original code is
```css
.markdown-source-view .codeblock-customizer-header-container, .markdown-source-view .codeblock-customizer-header-container-specific {
    width: calc(var(--line-width-adaptive) - var(--folding-offset));
    margin-left: max(calc(50% + var(--folding-offset) - var(--line-width-adaptive)/2), calc(50% + var(--folding-offset) - var(--max-width)/2)) !important;
}
```
